export const UI_STRINGS = {
  zh: {
    templates: "Templates / 模板",
    editor: "内容编辑",
    langZh: "仅中文",
    langEn: "仅英文",
    langDual: "中英对照",
    exportBtn: "Export PDF / 导出 PDF",
    exporting: "导出中…",
    printBtn: "Print / 打印",
    version: "Version / 版本",
    updated: "Last Updated / 更新日期",
    uiLangLabel: "界面语言 / Language",
    letterLangLabel: "信件语言",
    catEmployment: "雇主信类",
    catNotice: "通知与申请类",
    catTermination: "离职与解雇类",
    collapse: "折叠",
    expand: "展开",
    expandEditor: "展开内容编辑",
    expandTemplates: "展开模板",
    modeLabel: "编辑模式",
    batchMode: "批量模式",
    singleMode: "单人模式",
    downloadTemplate: "下载 Excel 模版",
    uploadCsv: "上传数据表格 (.xlsx)",
    batchSummary: "共识别到 {count} 条数据",
    startBatch: "开始批量生成 (ZIP)",
    batchProgress: "正在生成第 {current}/{total} 份...",
    batchComplete: "批量生成完成！",
    batchError: "表格格式有误，请检查标题行",
    batchNote: "请确保表格列名与输入框标签完全一致",
    addRecord: "手动新增",
    batchEmpty: "暂无数据",
    addRecordHint: "如需手动添加数据，请点击",
    uploadData: "上传数据表格",
    previewOnly: "仅显示前 10 条预览",
  },
  en: {
    templates: "Templates",
    editor: "Editor",
    langZh: "Chinese Only",
    langEn: "English Only",
    langDual: "Bilingual",
    exportBtn: "Export PDF",
    exporting: "Exporting...",
    printBtn: "Print",
    version: "Version",
    updated: "Last Updated",
    uiLangLabel: "界面语言 / Language",
    letterLangLabel: "Letter Language",
    catEmployment: "Employment Letters",
    catNotice: "Notices & Requests",
    catTermination: "Separation & Termination",
    collapse: "Collapse",
    expand: "Expand",
    expandEditor: "Expand Editor",
    expandTemplates: "Expand Templates",
    modeLabel: "Editor Mode",
    batchMode: "Batch Mode",
    singleMode: "Single Mode",
    downloadTemplate: "Download Excel Template",
    uploadData: "Upload Excel Data",
    addRecord: "Add Record",
    uploadCsv: "Upload Data (.xlsx)",
    batchSummary: "Recognized {count} records",
    startBatch: "Start Batch Generation (ZIP)",
    batchProgress: "Generating {current}/{total}...",
    batchComplete: "Batch Complete!",
    batchError: "File format error, please check headers",
    batchNote: "Ensure Excel column names match input labels exactly",
    batchEmpty: "No data found",
    addRecordHint: "To add data manually, please click",
    previewOnly: "Showing first 10 records only",
  }
};

export const CURRENCY_FIELDS = ['salary', 'monthlyBase', 'annualSalary', 'bonus', 'annualBonus', 'statutoryComp', 'extraComp', 'grossSalary'];
export const UNIT_FIELDS = ['noticePeriod'];

export const UNIT_TRANSLATIONS = {
  zh: { day: '天', month: '个月' },
  en: { day: 'day(s)', month: 'month(s)' }
};

export const REQUIRED_FIELDS = ['employeeName', 'role', 'startDate'];
